Datefeat
sqreen/tor-test pull request #2
Opened 2016-12-13 16:33 UTC by vouill

Hello Sqreen,
I was lurking in your repos and found this one.

Unless i missed something, if a new tor exit node appears, and the server using this lib haven't been restarted, the connections coming from it wont be refused, unless a `force` argument is given.

I was wondering if it could be a good idea to use the date you send at each API responses to make the library self aware of how long since the last IP store have been updated. 
In this PR i have made  a simple test, if the latest store refresh is 1 month old max.

Since i am not sure of the validity of this issue, i haven't adapted the test files. If you think its a good idea i can adapt them.

Vouill

2016-12-14 09:12 UTC, vdeturckheim commented
@vouill thanks a lot for contributing!
It looks pretty fair as a change. However, I think it would be better as an optional feature:
* adding a method named for instance `refreshStoreOlderThan` that would set the max age for the cache.
* by default there would be no update due to an old cache

What do you think about that ? :)

2016-12-14 13:31 UTC, vouill commented
Seems good to me. I'll add the necessary changes to this PR then.

2016-12-14 21:37 UTC, vouill commented
If you can review my PR, you can now set a number of days before auto refresh of the cache.

2016-12-15 18:24 UTC, vdeturckheim requested changes
Just a few cosmetic changes and it will be good :)

2016-12-15 18:24 UTC, vdeturckheim commented on lib/store.js
> +    return false;
inline lines 75 to 78:
`return diffDays >= maxInterval`

2016-12-15 18:24 UTC, vdeturckheim commented on lib/store.js
> +        return cb(new Error('refreshStoreOlderThan(arg) is not an integer'));
change message to 'maxdays must be an integer'

2016-12-16 15:15 UTC, vdeturckheim approved these changes

2016-12-16 15:15 UTC, merged

2016-12-16 15:15 UTC, vdeturckheim commented
@vouill thanks a lot for this PR!

2016-12-16 15:17 UTC, vouill commented
@vdeturckheim I am glad to help !